name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Run tests
    - name: Run tests
      run: npm test

    # Step 5: Notify on failure
    - name: Notify on failure
      if: failure()
      run: echo "Tests failed!"

    # Step 6: Deploy to production if tests pass
    - name: Deploy to production
      if: success()
      run: |
        echo "Tests passed! Deploying to production..."
        # Add your deployment commands here, e.g., FTP upload, or a script
